config/routes.rb
Rails.application.routes.draw do
  root 'rap_sheet_pdf#new'

  resources :users do
    scope module: :users do
      resource :contact_information, only: [:show, :edit, :update]
      resource :financial_information, only: [:new, :create]
      resource :benefits, only: [:new, :create]
      resource :income_information, only: [:new, :create]
      resource :legal_representations, only: [:new] do
        collection do
          post :yes
          post :no
        end
      end
    end
    resources :attorneys, only: [:new, :create]
  end


  resources :rap_sheets, only: [:index, :edit, :show, :create] do
    member do
      get :no_convictions
      get :debug
      put :add_page
      put :remove_page
    end

    resources :documents, only: [:index] do
      collection do
        get :download
      end
    end
  end

  resources :rap_sheet_pdf, only: [:new, :create]

  resources :rap_sheet_pages, only: [:create, :destroy]
  get 'healthcheck', to: proc { [200, {}, ['']] }

  mount Cfa::Styleguide::Engine => "/cfa"

  # keep last
  match '*path', via: [:all], to: 'application#not_found'
end

app/models/rap_sheet.rb
class RapSheet < ApplicationRecord
  belongs_to :user

  has_many :rap_sheet_pages

  validates :number_of_pages, numericality: {
    only_integer: true,
    less_than: 100,
    greater_than_or_equal_to: 1
  }

  def text
    rap_sheet_pages.map(&:text).join
  end

  def first_missing_page_number
    ((1..number_of_pages).to_a - rap_sheet_pages.pluck(:page_number)).first
  end

  def all_pages_uploaded?
    rap_sheet_pages.length == number_of_pages
  end

  def parsed
    @parsed ||= RapSheetParser::Parser.new.parse(text)
    if @parsed.personal_info
      unless user.name.present? && user.date_of_birth.present?
        user.update!(name: @parsed.personal_info.names.first.second, date_of_birth: @parsed.personal_info.date_of_birth)
        user.format_name
      end
    end
    @parsed
  end
end

app/controllers/rap_sheets_controller.rb
include ActionView::Helpers::TextHelper

class RapSheetsController < ApplicationController
  def index
    @rap_sheet = RapSheet.new
  end

  def edit
    @rap_sheet = RapSheet.find(params[:id])

    @rap_sheet_pages = (1..@rap_sheet.number_of_pages).map do |n|
      RapSheetPage.find_or_initialize_by(
        page_number: n,
        rap_sheet: @rap_sheet
      )
    end
  end

  def show
    @rap_sheet = RapSheet.find(params[:id])
    @transcript = TranscriptPresenter.new(@rap_sheet)
    if @rap_sheet.parsed.convictions.length == 0
      redirect_to no_convictions_rap_sheet_path(@rap_sheet)
    end
    @user_name = @rap_sheet.user.name.titlecase
    eligibility = EligibilityChecker.new(@rap_sheet.parsed)
    if eligibility.eligible?
      @remedy_names = EligibilityChecker::REMEDIES.map { |r| [r[:key], r[:name]] }.to_h
      eligible_events = eligibility.eligible_events_with_counts
      @eligible_events_by_remedy = {}

      EligibilityChecker::REMEDIES.each do |remedy|
        selected_events = eligible_events.select { |e| e[remedy[:key]][:counts].present? }
        grouped_events = selected_events.group_by { |e| e[:event].courthouse }
        @eligible_events_by_remedy[remedy[:key]] = grouped_events
      end
      @eligible_counts = eligibility.all_eligible_counts
      number_of_eligible_counts = @eligible_counts.values.flatten.uniq.length
      eligible_counts_string = pluralize(number_of_eligible_counts, 'conviction')
      @header_copy = "We found #{eligible_counts_string} that may be eligible for record clearance."
    else
      @no_eligible_convictions = true
      @header_copy = 'We found no convictions eligible for relief at this time.'
    end
  end

  def create
    @rap_sheet = RapSheet.new(rap_sheet_params.merge(user: User.new))
    if @rap_sheet.save
      redirect_to edit_rap_sheet_path(@rap_sheet)
    else
      render :index
    end
  end

  def debug
    @rap_sheet = RapSheet.find(params[:id])
    begin
      @conviction_events = @rap_sheet.parsed.convictions
    rescue RapSheetParser::RapSheetParserException => e
      @conviction_events = []
      @rap_sheet_parse_error = e
      @wrapped_error = ActionDispatch::ExceptionWrapper.new(Rails::BacktraceCleaner.new, e)
    end
  end

  def ineligible
    @rap_sheet = RapSheet.find(params[:id])
  end

  def add_page
    @rap_sheet = RapSheet.find(params[:id])
    @rap_sheet.update(number_of_pages: @rap_sheet.number_of_pages + 1)

    redirect_to edit_rap_sheet_path(@rap_sheet)
  end


  def remove_page
    @rap_sheet = RapSheet.find(params[:id])

    if @rap_sheet.number_of_pages > 1
      last_page = @rap_sheet.rap_sheet_pages.find_by(page_number: @rap_sheet.number_of_pages)
      last_page.destroy if last_page

      @rap_sheet.update!(number_of_pages: @rap_sheet.number_of_pages - 1)
    end

    redirect_to edit_rap_sheet_path(@rap_sheet)
  end

  private

  def rap_sheet_params
    params.require(:rap_sheet).permit(:number_of_pages)
  end

  rescue_from RapSheetParser::RapSheetParserException do |exception|
    redirect_to debug_rap_sheet_path(@rap_sheet)
  end
end

app/views/rap_sheets/_summary_table.html.erb
<div class="summary-table">
  <table>
    <caption><%= courthouse %></caption>
    <% events.each do |event| %>
      <% event[remedy][:counts].each do |conviction_count| %>
        <tr>
          <td><%= event[:event].date&.strftime('%m/%d/%Y') %></td>
          <td><%= conviction_count.disposition&.severity %></td>
          <td><%= conviction_count.code_section %></td>
          <td><%= conviction_count.code_section_description&.titleize %></td>
          <td>#<%= event[:event].case_number %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/rap_sheets/_summary_table_rows.html.erb
    <tr><th class="minor-header" colspan="5"><%= courthouse %></th></tr>
    <% events.each do |event| %>
      <% event[remedy][:counts].each do |conviction_count| %>
        <tr>
          <td><%= event[:event].date&.strftime('%m/%d/%Y') || '–' %></td>
          <td><%= conviction_count.severity || '–' %></td>
          <td><%= conviction_count.code_section || '–' %></td>
          <td><%= conviction_count.code_section_description&.titleize || '–' %></td>
          <td>#<%= event[:event].case_number || '–' %></td>
        </tr>
      <% end %>
    <% end %>

app/views/rap_sheets/debug.erb
<% @title="Error" %>
<div id="errorPage">
  <div class="slab">
    <%= render 'shared/error_card', error_title: 'Upload error', error_message: "Apologies, we weren't able to read the file you uploaded", show_emoji: true%>
    <div class="row">
      <div class="col-sm-2">
        <button id='errorButton' class="pattern__button margin-left" @click='toggle()'>
          More information<i v-bind:class="[isOpen ? 'icon-arrow_drop_up' : 'icon-arrow_drop_down']"></i>
        </button>
      </div>
    </div>
    <div id="errorContent" v-show="isOpen">
      <% if @rap_sheet_parse_error %>
        <p class="rap-sheet-debug-page-marker">Error!</p>
        <p>There was a problem parsing your RAP sheet. Here's some technical details:</p>
        <pre class="rap-sheet-debug-backtrace"><%= @rap_sheet_parse_error.message %><%= "\n\n" %><%= @wrapped_error.application_trace.join("\n") %></pre>
      <% else %>
        <h1>Here is your rap sheet:</h1>
      <% end %>

      <%= link_to(download_summary_rap_sheet_documents_path(@rap_sheet), data: { turbolinks: false }) do %>
        Download RAP sheet summary
      <% end %>

      <% if @conviction_events.present? %>
        <p class="rap-sheet-debug-page-marker">Convictions:</p>
        <div class="border">
          <table>
            <thead>
            <tr>
              <th>Date</th>
              <th>Case#</th>
              <th>Courthouse</th>
              <th>Sentence</th>
              <th>Counts</th>
            </tr>
            </thead>
            <tbody>
            <% @conviction_events.each do |conviction_event| %>
              <tr>
                <td style="white-space: nowrap;"><%= conviction_event.date %></td>
                <td><%= conviction_event.case_number %></td>
                <td><%= conviction_event.courthouse %></td>
                <td><%= conviction_event.sentence %></td>
                <td>
                  <ul>
                    <% conviction_event.counts.each do |count| %>
                      <li><%= "#{ count.code_section} --- #{count.code_section_description }" %></li>
                    <% end %>
                  </ul>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

      <% @rap_sheet.rap_sheet_pages.each.with_index do |r, i| %>
        <p class="rap-sheet-debug-page-marker">Page <%= i + 1 %>:</p>
        <pre><%= r.text %></pre>
      <% end %>
    </div>
  </div>
</div>

<script>
  new Vue({
      el: '#errorPage',
      data: {
          isOpen: false
      },
      methods: {
          toggle: function () {
              this.isOpen = !this.isOpen
          }
      }
  })
</script>

app/views/rap_sheets/edit.html.erb
<div class="container">
  <h1 class="mt-5 font-weight-normal">Upload all <%= pluralize(@rap_sheet.number_of_pages, 'page') %> of your RAP
    sheet</h1>
  <p>Please make sure to:</p>
  <ul>
    <li>Photograph one page at a time</li>
    <li>Keep the pages in order</li>
    <li>Take a clear photo, so the words aren't blurry</li>
  </ul>

  <p class="mt-4"><%= @rap_sheet.rap_sheet_pages.length %> of <%= pluralize(@rap_sheet.number_of_pages, 'page') %> uploaded</p>

  <div class="card">
    <div class="card-content">
      <ul class="list-group list-group-flush">
        <% @rap_sheet_pages.each do |rap_sheet_page| %>
          <li class="list-group-item">
            <%= content_tag :div, class: 'rap-sheet-page-row', id: "rap_sheet_page_#{rap_sheet_page.page_number}" do %>
              <div class="rap-sheet-page-number-column">
                <%= content_tag :div, class: "mr-2 page-indicator #{rap_sheet_page.persisted? ? 'completed' : ''}" do %>
                  <%= rap_sheet_page.page_number %>
                <% end %>
              </div>
              <div class="rap-sheet-page-content">
                <%= form_for rap_sheet_page, url: rap_sheet_pages_path, method: :post, html: { multipart: true } do |f| %>
                  <div>
                    page <%= rap_sheet_page.page_number %><% if rap_sheet_page.persisted? %> uploaded<% end %>
                  </div>
                  <% if rap_sheet_page.persisted? %>
                    <%= rap_sheet_page.rap_sheet_page_image.file.filename %>
                  <% elsif rap_sheet_page.page_number == @rap_sheet.first_missing_page_number %>
                    <label class="mt-1 btn btn-info btn-sm">
                      + add
                      <%= f.file_field :rap_sheet_page_image, accept: 'image/*', capture: 'camera', class: 'hidden' %>
                    </label>
                  <% end %>
                  <%= f.hidden_field :rap_sheet_id %>
                  <%= f.hidden_field :page_number %>
                  <div><%= f.submit 'Upload', class: 'hidden' %></div>
                <% end %>
              </div>
              <% if rap_sheet_page.persisted? %>
                <div class="rap-sheet-page-delete"><%= button_to '×', rap_sheet_page_path(rap_sheet_page), method: :delete %></div>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= button_to '+ add a page', add_page_rap_sheet_path(@rap_sheet), form_class: 'd-inline', class: 'btn btn-link', method: :put %>
  <% if @rap_sheet.number_of_pages > 1 %>
    <%= button_to '- remove a page', remove_page_rap_sheet_path(@rap_sheet), form_class: 'd-inline', class: 'btn btn-link', method: :put %>
  <% end %>

  <p class="mt-4">
    <% if @rap_sheet.all_pages_uploaded? %>
      All <%= pluralize(@rap_sheet.number_of_pages, 'page') %> added!
    <% else %>
      Upload <%= pluralize(@rap_sheet.number_of_pages, 'page') %> before proceeding
    <% end %>
  </p>
  <%= link_to 'Next →', rap_sheet_path(@rap_sheet), class: "btn btn-info mt-2 #{'disabled' unless @rap_sheet.all_pages_uploaded?}" %>
</div>

<script type="text/javascript" charset="utf-8">
  $('input[type="file"]').change(function (event) {
    $(this).closest('form').submit();
  });
</script>

app/views/rap_sheets/index.html.erb
<div class="container">
  <%= form_for @rap_sheet do |f| %>
    <div class="form-group">
      <label>
        <h1 class="mt-5">How many pages does your RAP sheet have?</h1>

        <div class="row">
          <div class="col-sm-2">
            <%= f.number_field :number_of_pages, class: 'form-control' %>
          </div>
        </div>
      </label>
    </div>

    <% if @rap_sheet.errors.count > 0 %>
      <div id="error_explanation">
        <h2><%= pluralize(@rap_sheet.errors.count, "error") %> prohibited this rap sheet from being saved:</h2>

        <ul>
          <% @rap_sheet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.submit 'Next →', class: 'btn btn-info' %>
  <% end %>
</div>

app/views/rap_sheets/no_convictions.html.erb
<% @title="Error" %>
<div class="slab">
  <%= render 'shared/error_card', error_title: 'No convictions found', error_message: "We didn't find any convictions on the uploaded rap sheet.", show_emoji: false %>
</div>

app/views/rap_sheets/show.html.erb
<% @title="Transcript" %>
<div class="slab">
  <div class="form-card extra-wide-layout margin-top-large margin-bottom-large">
    <header class="form-card__header text--centered">
      <% unless @no_eligible_convictions %>
      <h1 class="big-emoji small_padding_bottom">😀</h1>
      <% end %>
      <p class="text--large"><%= @header_copy %></p>
    </header>
    <h2>Transcript - <%= @user_name %></h2>
    <table class="data-table">
      <thead>
      <tr>
        <th>Date</th>
        <th>County</th>
        <th>Case Number</th>
        <th>Grade</th>
        <th>Charge</th>
        <th>Probation</th>
        <th>Prison</th>
        <th>Remedy</th>
      </tr>
      </thead>
      <tbody>
      <% @transcript.rows.each do |row| %>
        <tr class=<%= 'divider' if row[:first_row_in_case?] %>>
          <td><%= row[:date] %></td>
          <td><%= row[:courthouse] %></td>
          <td><%= row[:case_number] %></td>
          <td><%= row[:severity] %></td>
          <td><%= row[:code_section] %></td>
          <td><%= row[:probation] %></td>
          <td><%= row[:prison] %></td>
          <td><%= row[:remedy] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="form-card__footer">
      <%= link_to 'Next →', new_user_legal_representations_path(@rap_sheet.user), class: 'button button--primary' %>
    </div>
  </div>
</div>