config/routes.rb
Rails.application.routes.draw do
  root 'rap_sheet_pdf#new'

  resources :users do
    scope module: :users do
      resource :contact_information, only: [:show, :edit, :update]
      resource :financial_information, only: [:new, :create]
      resource :benefits, only: [:new, :create]
      resource :income_information, only: [:new, :create]
      resource :legal_representations, only: [:new] do
        collection do
          post :yes
          post :no
        end
      end
    end
    resources :attorneys, only: [:new, :create]
  end


  resources :rap_sheets, only: [:index, :edit, :show, :create] do
    member do
      get :no_convictions
      get :debug
      put :add_page
      put :remove_page
    end

    resources :documents, only: [:index] do
      collection do
        get :download
      end
    end
  end

  resources :rap_sheet_pdf, only: [:new, :create]

  resources :rap_sheet_pages, only: [:create, :destroy]
  get 'healthcheck', to: proc { [200, {}, ['']] }

  mount Cfa::Styleguide::Engine => "/cfa"

  # keep last
  match '*path', via: [:all], to: 'application#not_found'
end

app/controllers/rap_sheet_pdf_controller.rb
class RapSheetPdfController < ApplicationController
  def new
    render :new, locals: { file_persisted: false }
  end

  def create
    rap_sheet = RapSheet.new(user: User.new)
    begin
      Dir.mktmpdir do |dir|
        image_paths = ConvertPdfToImages.convert(rap_sheet_pdf_params[:pdf_file].path, dir)
        rap_sheet.number_of_pages = image_paths.length
        rap_sheet.save!
        image_paths.each_with_index do |page, index|
          RapSheetPage.scan_and_create(
            image: File.new(page),
            rap_sheet: rap_sheet,
            page_number: index + 1
          )
        end
      end

      respond_to do |format|
        format.html { redirect_to rap_sheet_path(rap_sheet) }
        format.json { render json: rap_sheet }
      end

    rescue StandardError => error
      logger.error "Exception in RapSheetPdfController: #{error}'"
      render :error_page, :status => 500
    end
  end

  private

  def rap_sheet_pdf_params
    params.require(:rap_sheet_pdf).permit(:pdf_file)
  end
end

app/views/rap_sheet_pdf/error_page.html.erb
<% @title="Error" %>
<div class="slab">
<%= render 'shared/error_card', error_title: 'Upload error', error_message: "Apologies, we weren't able to read the file you uploaded", show_emoji: true%>
</div>

app/views/rap_sheet_pdf/new.html.erb
<% @title = "Upload File" %>
<div id="vue-app-div">
  <div class="slab">
    <div class="form-card form-card--wide" v-if="!loading && !error">
      <div class="form-card__header">
        <h1 class="form-card__title">Upload a California RAP sheet</h1>
      </div>

      <div class="form-card__content">
        <p>Select a PDF file to upload.</p>
        <%= form_for :rap_sheet_pdf, url: rap_sheet_pdf_index_path, remote: true, method: :post, html: { multipart: true, id: "rap_sheet_pdf_form", 'v-on:ajax:success': 'uploadSuccess', 'v-on:ajax:error': 'uploadError', 'data-type': 'json' } do |f| %>
          <div class="file-picker-box">
            <div class="flex-row">
              <label v-show="!selectedFile" class="button">
                Select file
                <%= f.file_field :pdf_file, { accept: 'application/pdf', class: 'hidden', 'v-on:change': 'fileInputChanged' } %>
              </label>
              <div v-cloak v-if="selectedFile" class="flex-row">
                <span class="truncate-text">PDF added: {{ selectedFile }}</span><i class="icon-close" v-on:click='clearFileInput'></i>
              </div>
              <div v-else>no file selected</div>
            </div>
          </div>

          <div class="form-card__footer">
            <%= f.submit 'Upload →', class: 'button button--primary', 'v-bind:disabled': '!selectedFile', "v-on:click": "uploadPDF" %>
          </div>
        <% end %>
      </div>
    </div>

    <div v-cloak class="form-card form-card--wide form-card--transition" v-if="loading && !error">
      <div class="form-card__header">
        <div v-if="!finishingUpload" class="emoji emoji--bigger emoji--woman-detective-medium-dark-skin-tone">Searching</div>
        <div v-cloak v-if="finishingUpload" class="emoji emoji--bigger emoji--clipboard">Almost Done</div>
        <h3 v-if="!finishingUpload" class="form-card__title margin-top-small">Searching for convictions that might be
          eligible for record
          clearance...</h3>
        <h3 v-cloak v-if="finishingUpload" class="form-card__title margin-top-small">Almost done! Just a few more
          seconds while we prepare your eligibility report...</h3>
      </div>
      <progress-bar v-bind:percent="percent"></progress-bar>
      <div class="form-card__footer">
        <button class="button" v-on:click="cancelLoad">Cancel</button>
      </div>
    </div>

    <div v-cloak class="form-card text--centered form-card--narrow" v-if="error">
      <div class="form-card--narrow">
        <h2 class="margin-top-med">Upload error</h2>
        <p class="text--large">Apologies, we weren't able to read the file you uploaded</p>
      </div>
      <div class="form-card__footer">
        <%= link_to 'Done', root_path, class: 'button button--primary' %>
      </div>
    </div>
  </div>
</div>

<script>
    function changeTitle(text) {
        document.title = text;
    }

    $(document).ready(function () {
        Vue.component('progress-bar', {
            props: ['percent'],
            template: `<div class="progress-indicator">
      <div class="progress-indicator__bar" :style="'width:' + percent + '%'"></div>
      <div class="progress-indicator__percentage">{{percent}}%</div>
      </div>`
        })

        var store = {
            selectedFile: null,
            loading: false,
            error: false,
            percent: 0,
            finishingUpload: false,
        };

        if ($('#vue-app-div').length) {
            new Vue({
                el: '#vue-app-div',
                data: store,
                methods: {
                    uploadSuccess: function (e) {
                        e.preventDefault();
                        console.log(e);
                        [rapSheet, statusCode, request] = e.detail;
                        window.location = '/rap_sheets/' + rapSheet['id'];
                    },
                    uploadError: function (e) {
                        changeTitle('Error');
                        store.error = true;
                    },
                    cancelLoad: function () {
                        window.location = '/';
                    },
                    fileInputChanged: function (event) {
                        console.log('file input changed');
                        store.selectedFile = event.target.files[0].name
                    },
                    clearFileInput: function () {
                        store.selectedFile = null;
                        document.getElementsByTagName('form')[0].reset();
                    },
                    uploadPDF: function () {
                        changeTitle('Checking Eligibility');
                        store.loading = true;
                        store.percent = 0;
                        tick = function () {
                            if (store.percent < 100) {
                                store.percent++;
                                store.tickMethod = window.setTimeout(tick, -6.5 * store.percent + 800)
                            } else {
                                store.finishingUpload = true;
                            }
                        }
                        tick();
                    }
                }

            });
        }
    });
</script>