config/routes.rb
Rails.application.routes.draw do
  root 'rap_sheet_pdf#new'

  resources :users do
    scope module: :users do
      resource :contact_information, only: [:show, :edit, :update]
      resource :financial_information, only: [:new, :create]
      resource :benefits, only: [:new, :create]
      resource :income_information, only: [:new, :create]
      resource :legal_representations, only: [:new] do
        collection do
          post :yes
          post :no
        end
      end
    end
    resources :attorneys, only: [:new, :create]
  end


  resources :rap_sheets, only: [:index, :edit, :show, :create] do
    member do
      get :no_convictions
      get :debug
      put :add_page
      put :remove_page
    end

    resources :documents, only: [:index] do
      collection do
        get :download
      end
    end
  end

  resources :rap_sheet_pdf, only: [:new, :create]

  resources :rap_sheet_pages, only: [:create, :destroy]
  get 'healthcheck', to: proc { [200, {}, ['']] }

  mount Cfa::Styleguide::Engine => "/cfa"

  # keep last
  match '*path', via: [:all], to: 'application#not_found'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :rap_sheet
  has_one :financial_information
  belongs_to :attorney, optional: true

  def format_name
    name_array = name.split(',')
    return if name_array.length < 2
    formatted_name = name_array[1] + ' ' + name_array[0]
    update!(name: formatted_name)
  end
end

app/controllers/users/benefits_controller.rb
module Users
  class BenefitsController < ApplicationController
    def new
      @user = User.find(params[:user_id])
    end

    def create
      @user = User.find(params[:user_id])
      @user.financial_information.update!(benefits_params)
      if benefits_params[:benefits_programs].empty?
        redirect_to new_user_income_information_path(@user)
      else
        redirect_to rap_sheet_documents_path(@user.rap_sheet)
      end
    end

    private

    def benefits_params
      _benefits_params = params.require(:financial_information).permit(benefits_programs: [])
      _benefits_params[:benefits_programs].reject!(&:blank?)
      _benefits_params
    end
  end
end

app/controllers/users/contact_informations_controller.rb
module Users
  class ContactInformationsController < ApplicationController
    def show
      @user = User.find(params[:user_id])
      redirect_to edit_user_contact_information_path(@user)
    end

    def edit
      @user = User.find(params[:user_id])
      @form = ContactInformationForm.from_user(@user)
      #redirect_to rap_sheet_documents_path(@user.rap_sheet)
    end

    def update
      @user = User.find(params[:user_id])
      @form = ContactInformationForm.new(contact_information_params)
      if @form.save(@user)
        redirect_to rap_sheet_documents_path(@user.rap_sheet)
      else
        render :edit
      end
    end

    private

    def contact_information_params
      params.require(:contact_information_form).permit(
        :name,
        :phone_number,
        :email,
        :street_address,
        :city,
        :state,
        :zip,
        :date_of_birth,
        :prefer_email,
        :prefer_text
      )
    end
  end
end

app/controllers/users/financial_informations_controller.rb
module Users
  class FinancialInformationsController < ApplicationController
    def new
      @user = User.find(params[:user_id])
      @financial_information = FinancialInformation.new(user: @user)
    end

    def create
      user = User.find(params[:user_id])

      financial_information = FinancialInformation.find_or_initialize_by(user: user)

      if params[:financial_information][:employed] == 'false'
        params[:financial_information][:job_title] = nil
        params[:financial_information][:employer_name] = nil
        params[:financial_information][:employer_address] = nil
      end

      financial_information.update!(financial_information_params)
      redirect_to new_user_benefits_path(user)
    end

    private

    def financial_information_params
      params.require(:financial_information).permit(:employed, :job_title, :employer_name, :employer_address)
    end
  end
end

app/controllers/users/income_informations_controller.rb
module Users
  class IncomeInformationsController < ApplicationController
    def new
      @user = User.find(params[:user_id])
    end

    def create
      user = User.find(params[:user_id])
      user.financial_information.update!(income_information_params)
      redirect_to rap_sheet_documents_path(user.rap_sheet)
    end

    private

    def income_information_params
      params.require(:financial_information).permit(:household_size, :monthly_income_limit, :monthly_income_under_limit)
    end
  end
end

app/controllers/users/legal_representations_controller.rb
module Users
  class LegalRepresentationsController < ApplicationController
    def new
      @user = User.find(params[:user_id])
    end

    def yes
      @user = User.find(params[:user_id])
      @user.update(has_attorney: true)
      redirect_to new_user_attorney_path(@user)
    end

    def no
      @user = User.find(params[:user_id])
      @user.update(has_attorney: false)
      redirect_to user_contact_information_path(@user)
    end
  end
end

app/views/users/income_informations/new.html.erb
<div class="container">
  <h1 class="mt-5">Financial Information</h1>
  <hr>
  <p>Some courts require that you pay up to $300 per petition to clear your record. This information will only be used
    by the court to check if you qualify for a fee waiver.</p>

  <%= form_for @user.financial_information, url: user_income_information_path(@user), method: :post do |f| %>
    <%= f.hidden_field :monthly_income_limit %>
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :household_size, 'How many people do you live with, including yourself?' %>
          <%= f.number_field :household_size, class: 'form-control', required: true %>
        </div>
        <%= content_tag :div, class: "form-group #{f.object.household_size ? '' : 'hidden'}", data: { visible_by: 'financial_information[household_size]' } do %>
          <%= f.label :monthly_income_under_limit do %>
            Is your monthly income less than
            $<span id="monthly_income_limit_amount"></span>?
          <% end %>
          <%= render 'shared/yes_no_radio', f: f, field: :monthly_income_under_limit, required: true %>
        <% end %>
      </div>
    </div>
    <%= f.submit 'Next →', class: 'btn btn-info' %>
  <% end %>
</div>
<script>
  baseMonthlyIncomeLimit = <%= FinancialInformation::BASE_MONTHLY_INCOME_LIMIT %>;
  householdSizeIncomeModifier = <%= FinancialInformation::HOUSEHOLD_SIZE_INCOME_MODIFIER %>;
</script>